// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"golang.org/x/sync/errgroup"
	"week04/internal/biz"
	"week04/internal/conf"
	"week04/internal/data"
	"week04/internal/data/ent"
	"week04/internal/server"
	"week04/internal/service"
)

// Injectors from wire.go:

// initApp Inject wire ProvideSet
func initApp(group *errgroup.Group, option conf.Options) *App {
	client := data.NewEntClient(option)
	httpBookRepo := service.NewHTTPBookRepo(client)
	httpBookBusiness := biz.NewHttpBookBusiness(httpBookRepo)
	engine := server.NewHttpRouter(option, httpBookBusiness)
	httpServer := server.NewHttpServer(group, option, engine)
	grpcBookService := service.NewGRPCBookService(client)
	grpcServer := server.NewGRPCServer(group, option, grpcBookService)
	app := newApp(httpServer, grpcServer, client)
	return app
}

// wire.go:

type App struct {
	HttpServer *server.HttpServer
	GRPCServer *server.GRPCServer
	Client     *ent.Client
}

// newApp return App struct with server.HttpServer and server.GRPCServer
func newApp(http *server.HttpServer, grpc *server.GRPCServer, client *ent.Client) *App {
	return &App{HttpServer: http, GRPCServer: grpc, Client: client}
}
