// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"homework/internal"
	"homework/service"
)

// Injectors from wire.go:

//go:generate
func InitializeApp() *service.App {
	config := internal.AppConf()
	appServer := service.NewAppServer(config)
	rpcServer := service.NewRpcServer(config)
	signalHandler := service.NewSignalHandler()
	app := service.NewApp(appServer, rpcServer, signalHandler)
	return app
}
